name: Deploy site to GitHub Pages

on:
    repository_dispatch:
        types:
            - deploy

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: github-pages
                  repository: ${{ secrets.SOURCE_REPOSITORY }}
                  run-id: ${{ github.event.client_payload.run_id }}
                  github-token: ${{ secrets.GH_PAT }}
                  path: deploy/github-pages

            - uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: deploy/github-pages

            - id: deployment
              uses: actions/deploy-pages@v4
